#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist


if __name__ == "__main__": #incio del programa

    #Inicializar nodo
    rospy.init_node('nodo_publicador_move_robot')

    #publicador
    topic = 'cmd_vel' 
    pub = rospy.Publisher(topic, Twist, queue_size=1)

    # Creación de una instancia (vacía) del mensaje
    twist_msg = Twist()

    # Tiempo de ejecución del bucle (en Hz)
    rate = rospy.Rate(10)    

    try: #pub de msg cada 0.1x30 = 3ss
        rospy.loginfo("Avanzando recto . . .")
        twist_msg.linear.x = 0.2
        twist_msg.angular.z= 0.0
        for _ in range(40):
            pub.publish(twist_msg)
            rate.sleep()

        rospy.loginfo("Girando . . .")
        twist_msg.linear.x = 0.1
        twist_msg.angular.z= 0.4
        for _ in range(75):
            pub.publish(twist_msg)
            rate.sleep()


        rospy.loginfo("Avanzando recto . . .")
        twist_msg.linear.x = 0.2
        twist_msg.angular.z= 0.0
        for _ in range(40):
            pub.publish(twist_msg)
            rate.sleep()

        # Parar el robot al final
        rospy.loginfo("Deteniendo el robot.")
        twist_msg.linear.x = 0.0
        twist_msg.angular.z= 0.0
        pub.publish(twist_msg)
    
    except rospy.ROSInitException:
        pass



