#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Point


class SuscriptorPoint(object):
    def __init__(self):
        topic = 'topic_point'
        self.sub = rospy.Subscriber(topic, Point, self.callback_func)
        self.rangos = [0.0]*5 

    # Función de callback
    def callback_func(self,msg):
        print("Punto leido: x={}, y={}, z={}".format(msg.x, msg.y, msg.z))



if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_point')

    # Declaración del suscriptor
    sub = SuscriptorPoint()

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

