#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Quaternion


class SuscriptorQuat(object):
    def __init__(self):
        topic = 'topic_quat'
        self.sub = rospy.Subscriber(topic, Quaternion, self.callback_func)


    # Función de callback
    def callback_func(self,msg):
        print("Cuaternion leido: w={}, x={}, y={}, z={}".format(msg.w, msg.x, msg.y, msg.z))



if __name__ == "__main__": # Inicio del programa principal

    # Inicializar el nodo
    rospy.init_node('nodo_suscriptor_quat')

    # Declaración del suscriptor
    SuscriptorQuat()

    # Mantener el nodo activo (hasta que se detenga
    rospy.spin()

